// Code generated by MockGen. DO NOT EDIT.
// Source: eaglebank/internal/domain/transaction (interfaces: Transaction)
//
// Generated by this command:
//
//	mockgen -destination=../../infrastructure/persistence/transaction/mock/account-mock.go -package=mock . Transaction
//

// Package mock is a generated GoMock package.
package mock

import (
	transaction "eaglebank/internal/domain/transaction"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
	isgomock struct{}
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// BelongToUser mocks base method.
func (m *MockTransaction) BelongToUser(accountNumber, transactionId string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BelongToUser", accountNumber, transactionId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BelongToUser indicates an expected call of BelongToUser.
func (mr *MockTransactionMockRecorder) BelongToUser(accountNumber, transactionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BelongToUser", reflect.TypeOf((*MockTransaction)(nil).BelongToUser), accountNumber, transactionId)
}

// Create mocks base method.
func (m *MockTransaction) Create(entity transaction.TransactionEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTransactionMockRecorder) Create(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransaction)(nil).Create), entity)
}

// Get mocks base method.
func (m *MockTransaction) Get(transactionNumber string) (transaction.TransactionEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", transactionNumber)
	ret0, _ := ret[0].(transaction.TransactionEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTransactionMockRecorder) Get(transactionNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransaction)(nil).Get), transactionNumber)
}

// List mocks base method.
func (m *MockTransaction) List(accountNumber string) ([]transaction.TransactionEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", accountNumber)
	ret0, _ := ret[0].([]transaction.TransactionEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTransactionMockRecorder) List(accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTransaction)(nil).List), accountNumber)
}
