// Code generated by MockGen. DO NOT EDIT.
// Source: eaglebank/internal/domain/account (interfaces: Account)
//
// Generated by this command:
//
//	mockgen -destination=../../infrastructure/persistence/account/mock/account-mock.go -package=mock . Account
//

// Package mock is a generated GoMock package.
package mock

import (
	account "eaglebank/internal/domain/account"
	reflect "reflect"

	decimal "github.com/shopspring/decimal"
	gomock "go.uber.org/mock/gomock"
)

// MockAccount is a mock of Account interface.
type MockAccount struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMockRecorder
	isgomock struct{}
}

// MockAccountMockRecorder is the mock recorder for MockAccount.
type MockAccountMockRecorder struct {
	mock *MockAccount
}

// NewMockAccount creates a new mock instance.
func NewMockAccount(ctrl *gomock.Controller) *MockAccount {
	mock := &MockAccount{ctrl: ctrl}
	mock.recorder = &MockAccountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccount) EXPECT() *MockAccountMockRecorder {
	return m.recorder
}

// BelongToUser mocks base method.
func (m *MockAccount) BelongToUser(userId, accountNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BelongToUser", userId, accountNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BelongToUser indicates an expected call of BelongToUser.
func (mr *MockAccountMockRecorder) BelongToUser(userId, accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BelongToUser", reflect.TypeOf((*MockAccount)(nil).BelongToUser), userId, accountNumber)
}

// Create mocks base method.
func (m *MockAccount) Create(entity account.AccountEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAccountMockRecorder) Create(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAccount)(nil).Create), entity)
}

// Delete mocks base method.
func (m *MockAccount) Delete(accountNumber string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", accountNumber)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAccountMockRecorder) Delete(accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccount)(nil).Delete), accountNumber)
}

// Get mocks base method.
func (m *MockAccount) Get(accountNumber string) (account.AccountEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", accountNumber)
	ret0, _ := ret[0].(account.AccountEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAccountMockRecorder) Get(accountNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAccount)(nil).Get), accountNumber)
}

// List mocks base method.
func (m *MockAccount) List(userId string) ([]account.AccountEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", userId)
	ret0, _ := ret[0].([]account.AccountEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccountMockRecorder) List(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccount)(nil).List), userId)
}

// NextAccountNumber mocks base method.
func (m *MockAccount) NextAccountNumber() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextAccountNumber")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextAccountNumber indicates an expected call of NextAccountNumber.
func (mr *MockAccountMockRecorder) NextAccountNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextAccountNumber", reflect.TypeOf((*MockAccount)(nil).NextAccountNumber))
}

// Update mocks base method.
func (m *MockAccount) Update(entity account.AccountEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAccountMockRecorder) Update(entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccount)(nil).Update), entity)
}

// UpdateBalance mocks base method.
func (m *MockAccount) UpdateBalance(accountNumber string, amount decimal.Decimal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", accountNumber, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockAccountMockRecorder) UpdateBalance(accountNumber, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccount)(nil).UpdateBalance), accountNumber, amount)
}
